### ISSUE TITLE
Error during docker compose

### ISSUE THREAD

**Issue by kajfik** [thexivn/RMT-Docker-server#3]
I have an error when running the `docker compose -f dockercompose.yml up` command:
```
time="2023-03-17T23:13:26+01:00" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string."
time="2023-03-17T23:13:26+01:00" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string."
[+] Running 3/4
 - Network rmt-docker-server-main_server-network  Created                                                                              0.7s
 - Container rmt-docker-server-main-database-1    Created                                                                              0.1s
 - Container rmt-docker-server-main-trackmania-1  Created                                                                              0.1s
 - Container rmt-docker-server-main-pyplanet-1    Creating                                                                             0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /settings/apps.py
```

I suspect this error pops up because I haven't modified the following line in dockercompose.yml:
```
PYPLANET_OWNER: changeIt #if u don't know your ID use /clam *** with the code reported when starting pyplanet
```
How do I start pyplanet and where do I put the `/clam ***` command?
Thank you for your time.

**Comment by thexivn** [comment]
About this error:
> Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /settings/apps.py

is caused because it can't find the /settings folder. Did  you correctly cloned all the project? Another reason could be because PWD is not set, this variable should be the dir in which you are running the command.

>where do I put the /clam *** command?

You put this inside the game after pyplanet start, because you need the code that pyplanet print in the console logs

**Comment by kajfik** [comment]
Thank you.
I didn't know where to set the PWD variable so I changed it directly in the `dockercompose.yml` file and now it works without issues 👍
Issue resolved, closing.
