### ISSUE TITLE
UDP initialization failed

### ISSUE THREAD

**Issue by WillWilli** [thexivn/RMT-Docker-server#4]
Hi, thanks for the docker-compose file. It seems to work ok, I am able to see the server from TM, but when I click 'join' or 'spectate' I get the error "UDP initialization failed". I dont suppose youve seen this before? 

Ive had a TM dedicated server on this machine before, just not within docker.

Thanks.

**Comment by thexivn** [comment]
With docker you need to open the port (2350) inside the firewall both for UDP and TCP

**Comment by WillWilli** [comment]
That was totally it! It's working great now. Thanks again.
