### ISSUE TITLE
Connectioon to master server failed

### ISSUE THREAD

**Issue by Waurick** [thexivn/RMT-Docker-server#5]
rmt-docker-server-trackmania-1  | Starting Trackmania date=2023-03-28_20_00 git=120685-f4c2211bf5b GameVersion=3.3.0...
rmt-docker-server-trackmania-1  | Configuration file : dedicated_cfg.txt
rmt-docker-server-trackmania-1  | Loading system configuration...
rmt-docker-server-trackmania-1  | ...system configuration loaded
rmt-docker-server-trackmania-1  | Loading dedicated server configuration...
rmt-docker-server-trackmania-1  | ...Dedicated server configuration loaded
rmt-docker-server-trackmania-1  | Connecting to master server...
rmt-docker-server-trackmania-1  | ...ERROR: Invalid credentials. (code NadeoServices/401)
rmt-docker-server-trackmania-1  | ERROR: Connection to master server lost. Exiting...
rmt-docker-server-trackmania-1  | Exiting...

Changed all the Secrets and tried inputing the Ownerid with my 
https://trackmania.io/#/player/4e60bf2e-79d7-4959-b097-cee702ae7671
login/Accountid 
both didn't work

help.

**Comment by thexivn** [comment]
Those credentials are related to TM server accounts. You can create a server account here https://www.trackmania.com/player/dedicated-servers
![image](https://user-images.githubusercontent.com/17314168/230604252-a1fdd59d-1547-4837-89bb-6265300fa416.png)

**Comment by 15009199** [comment]
- Container rmt-docker-server-main-pyplanet-1    Creating                                                         0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /settings/apps.py

Would this cause the Connection to master server failed? When setting up the server manually with the same credentials it works fine

**Comment by Waurick** [comment]
> 

This is a different Issue and related to this
<img width="548" alt="image" src="https://user-images.githubusercontent.com/71395103/230789695-deee1b58-f731-4b13-ab32-a810485515f5.png">

I want to make some modifications to the Readme and Docker Compose to make it more foolproof, but I don't know when I got time for it.  

Meanwhile, you can contact me on Discord if you have need immediate help. Or create a new Issue. Waurick#5555

**Comment by Waurick** [comment]
I will Close the Issue now because it was resolved 2 days ago.
