### ISSUE TITLE
invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by thexivn** [thexivn/RMT-Docker-server#7]
- Container rmt-docker-server-main-pyplanet-1    Creating                                                         0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /settings/apps.py

Would this cause the Connection to master server failed? When setting up the server manually with the same credentials it works fine

_Originally posted by @15009199 in https://github.com/thexivn/RMT-Docker-server/issues/5#issuecomment-1501182435_

**Comment by thexivn** [comment]
This problem is caused because on Windows the environment  variable is not set. 
You can run this command before the docker compose

PS:
```powershell
$env:PWD = pwd
```

CMD:
```cmd
set PWD=%cd%
```

**Comment by 15009199** [comment]
Thank you, it works fine now
